export type FormData = {
    id: number;
    submissionType: "employee" | "family";
    name: string;
    surname: string;
    gender: 'male' | 'female';
    pesel: string;
    birthDate: string;
    email: string;
    phone: string;
    street: string;
    houseNumber: string;
    flatNumber?: string;
    zip: string;
    postOffice: string;
    city: string;
    country: string;
    region: string;
    familyName?: string;
    familySurname?: string;
    familyGender?: 'male' | 'female';
    familyPesel?: string;
    familyIdentityMethod?: "pesel" | "birthDoc";
    familyBirthDate?: string;
    familyDocumentType?: 'dowod' | 'paszport';
    familyDocNumber?: string;
    familyIssuingCountry?: string;
    zgodaDanePrawdziwe: boolean;
    zgodaPrzetwarzanie: boolean;
    zgodaZapoznanie: boolean;
    createdAt?: string;
};